// src/wc/input/select.js
import svg from "../svg"
import { SelectOption } from "./select-option"

const template = document.createElement("template")

template.innerHTML = `
<style>
    :host {
        --items-length: 0;
        position: relative; 
        display: block;
        width: 100%;
        height: calc(1em * var(--line-height) + var(--spacing) * 2);
        border: var(--border-width) var(--border-style) hsl(var(--border));
        border-radius: var(--radius);
        font-size: 0.95em;
        overflow: hidden;
        transition: height 0.25s ease;
    }

    .options {
        cursor: pointer;
        display: none;
        display: flex;
        flex-direction: column;
        min-height: 100%;
    }

    .icon {
        display: flex;
        justify-content: center;
        align-items: center;
        position: absolute;
        top: 0;
        right: 0;
        width: 2.5em;
        height: 100%;
        color: hsl(var(--primary));
    }

    ::slotted(ui-select-option) {
        display: block;
    }

    :host(.open) {
        height: calc(
            (1em * var(--line-height) + var(--spacing) * 2) * var(--items-length)
        );
    }

    :host(.open) .options {
        display: block;
    }

    :host(.open) .icon {
        display: none;
    }

    :host(.open) ::slotted(ui-select-option[selected]) {
        background-color: hsl(var(--primary));
        color: hsl(var(--primary-fg));
    }

    :host(.open) ::slotted(ui-select-option:not([selected]):hover) {
        background-color: hsl(var(--fg), 0.1);
    }

    :host(:not(.open)) .options:has(> ::slotted(ui-select-option[selected])) {
        display: block;
    }

    :host(:not(.open)) ::slotted(ui-select-option:not([selected])) {
        display: none;
    }
</style>

<div class="options">
    <div slot="icon"></div>

    <slot></slot>
</div>
`

export class Select extends HTMLElement {
    #running = false;

    /** @param {Event} ev */
    #onOptionsClick = (ev) => {
        if (this.classList.toggle("open")) {
            ev.stopPropagation()
            this.addEventListener("click", this.#onClick)
        } else {
            setTimeout(() =>
                this.removeEventListener("click", this.#onClick)
            )
        }
    };

    /** @param {MouseEvent | PointerEvent} ev */
    #onClick = (ev) => {
        (ev.composedPath() || []).forEach(child => {
            if (child instanceof SelectOption) {
                [...this.querySelectorAll("ui-select-option")].forEach(c =>
                    c.removeAttribute("selected")
                );

                child.setAttribute("selected", "true");
                this.dispatchEvent(new CustomEvent("change", { detail: child }));
            }
        });
    };

    constructor() {
        super();
        this.attachShadow({ mode: "open" });
        this.shadowRoot.appendChild(template.content.cloneNode(true));

        const icon = new svg.ChevronDown();
        icon.setAttribute("slot", "icon");
        this.appendChild(icon);
    }

    /**
     * Runs each time the element is appended to or moved in the DOM
     */
    connectedCallback() {
        if (!this.#running) {
            this.shadowRoot.querySelector(".options")
                ?.addEventListener("click", this.#onOptionsClick);

            this.#running = true;
        }

        this.style.setProperty(
            "--items-length",
            this.querySelectorAll("ui-select-option")
                .length.toString()
        );
    }

    /**
     * Runs when the element is removed from the DOM
     */
    disconnectedCallback() {
        this.removeEventListener("click", this.#onClick);
        this.shadowRoot.querySelector(".options")?.addEventListener("click", this.#onOptionsClick);
        this.#running = false;
    }
}

// svelte/input/select/Select.svelte
<script>
	// TODO: move styles to css

	import { createEventDispatcher } from 'svelte';

	import ChevronDown from 'svelte-material-icons/ChevronDown.svelte';

	/**
	 * @typedef SelectItem
	 * @type {import(".").SelectItem}
	 */

	/******************************
	 * Variable Export Definitions
	 ******************************/

	/** @type {SelectItem[]} */
	export let items = [];

	/** @type {SelectItem | null} */
	export let selected = null;

	export let alwaysOpen = false;

	/***********************
	 * Variable Definitions
	 ***********************/

	const dispatch = createEventDispatcher();

	let open = alwaysOpen;

	/******************************
	 * Function Export Definitions
	 ******************************/

	export async function expand() {
		open = true;
	}

	export async function collapse() {
		open = false;
	}

	/***********************
	 * Function Definitions
	 ***********************/

	async function clickSelect() {
		open = !open;
	}

	/**
	 * @param {SelectItem} item
	 */
	async function clickOption(item) {
		selected = item;
		dispatch('change', item);
	}
</script>

<div
	{...$$restProps}
	class={'ui-input-select ' + ($$restProps.class || '')}
	class:open
	style:height={open
		? `calc((1em * var(--line-height) + (var(--spacing) * 2)) * ${items.length})`
		: 'calc(1em * var(--line-height) + (var(--spacing) * 2))'}
>
	<!-- svelte-ignore a11y-click-events-have-key-events -->
	<!-- svelte-ignore a11y-no-static-element-interactions -->
	<div
		class="options"
		style:display={!open && !selected ? 'none' : 'block'}
		on:click={!alwaysOpen ? () => clickSelect() : undefined}
	>
		<div class="icon"><ChevronDown height="100%" width="100%" /></div>

		{#each items as item}
			<div
				class="option no-user-select"
				class:selected={item.value === selected?.value}
				on:click={() => clickOption(item)}
			>
				<span>
					{item.label}
				</span>
			</div>
		{/each}
	</div>
</div>

<style>
	.ui-input-select {
		font-size: 0.95em;
		border: var(--border-width) var(--border-style) hsl(var(--border));
		border-radius: var(--radius);
		width: 100%;
		overflow: hidden;

		transition: height 0.25s ease;
	}

	.ui-input-select .options {
		cursor: pointer;
	}

	.ui-input-select .options .icon {
		display: flex;
		justify-content: center;
		align-items: center;
		position: absolute;
		top: 0;
		right: 0;
		bottom: 0;
		width: 2.5em;
		color: hsl(var(--primary));
	}

	.ui-input-select.open .options .icon {
		display: none;
	}

	.ui-input-select:not(.open) .options .option:not(.selected) {
		display: none;
	}

	.ui-input-select .options .option {
		height: 100%;
		padding: var(--spacing);
		padding-right: 2.5em;
		transition: background-color 0.25s linear;
	}

	.ui-input-select.open .options .option.selected {
		background-color: hsl(var(--primary));
		color: hsl(var(--primary-fg));
	}

	.ui-input-select.open .options .option:not(.selected):hover {
		background-color: hsl(var(--fg), 0.1);
	}
</style>
